from selenium import webdriver
import time

browser=webdriver.Firefox()
browser.get("https://www.instagram.com/")
time.sleep(2)
giris_yap=browser.find_element_by_xpath("//*[@id='react-root']/section/main/article/div[2]/div[2]/p/a")
giris_yap.click()
time.sleep(2)
username=browser.find_element_by_name("username")
password=browser.find_element_by_name("password")
username.send_keys("mymusices")
password.send_keys("cccgfreis3655")
login_instagram=browser.find_element_by_xpath("//*[@id='react-root']/section/main/div/article/div/div[1]/div/form/div[3]/button")
time.sleep(2)
login_instagram.click()
time.sleep(5)
profileButton=browser.find_element_by_xpath("//*[@id='react-root']/section/nav/div[2]/div/div/div[3]/div/div[3]/a")
profileButton.click()
time.sleep(2)
buttons=browser.find_elements_by_tag_name("//*[@id='react-root']/section/main/div/ul/li[2]/a")
print(buttons)
time.sleep(5)
browser.close()